<a href="https://colab.research.google.com/github/Ayan282/colab/blob/main/data_analiz1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

np.random.seed(42)
data = pd.DataFrame({
    "EmployeeID": np.arange(1, 31),
    "Name": [f"Emp{i}" for i in range(1, 31)],
    "Department": np.random.choice(["HR", "Sales", "IT", "Finance"], size=30),
    "JoiningDate": pd.to_datetime(np.random.choice(pd.date_range("2018-01-01", "2023-01-01"), size=30)),
    "Salary": np.random.randint(40000, 120000, size=30),
    "Bonus": np.random.randint(2000, 15000, size=30),
    "ExperienceYears": np.random.randint(1, 15, size=30),
    "ProjectsCompleted": np.random.randint(0, 30, size=30),
    "RemoteDays": np.random.randint(0, 50, size=30)
})

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays
0,1,Emp1,IT,2018-10-04,50627,9892,10,22,21
1,2,Emp2,Finance,2021-03-30,48792,8863,7,13,27
2,3,Emp3,HR,2019-04-05,113969,9916,10,6,1
3,4,Emp4,IT,2021-08-30,83001,10529,9,26,41
4,5,Emp5,IT,2018-01-22,116552,2878,12,8,44
5,6,Emp6,Finance,2018-09-10,63897,11268,7,14,5
6,7,Emp7,HR,2020-01-18,108148,6887,9,14,27
7,8,Emp8,HR,2020-05-06,63483,14185,8,25,27
8,9,Emp9,IT,2022-05-04,88555,6859,12,9,43
9,10,Emp10,Sales,2019-04-20,57159,8331,2,27,43
10,11,Emp11,IT,2020-12-18,75920,10571,1,12,19
11,12,Emp12,IT,2019-05-26,107121,10684,7,18,29
12,13,Emp13,IT,2022-09-02,109479,9208,7,6,10
13,14,Emp14,IT,2022-02-08,59457,7276,14,16,27
14,15,Emp15,Finance,2019-12-01,106557,4062,8,19,24
15,16,Emp16,HR,2020-09-02,117189,14076,5,28,38
16,17,Emp17,Finance,2022-12-12,118953,2064,3,3,32
17,18,Emp18,Finance,2018-07-09,92995,10006,12,29,0
18,19,Emp19,Finance,2020-08-15,80757,4568,8,4,26
19,20,Emp20,IT,2019-11-18,49692,7463,6,22,12
20,21,Emp21,Sales,2020-08-15,85758,4027,11,6,40
21,22,Emp22,HR,2019-07-17,112409,4695,3,12,2
22,23,Emp23,Sales,2022-05-10,111211,11687,1,14,38
23,24,Emp24,Finance,2021-06-21,105697,7258,3,10,5
24,25,Emp25,Finance,2020-04-11,77065,7618,5,28,7
25,26,Emp26,Sales,2022-03-09,72606,8736,14,3,26
26,27,Emp27,Sales,2021-02-28,51534,2391,3,12,8
27,28,Emp28,Sales,2022-02-17,80397,14706,1,6,36
28,29,Emp29,Finance,2019-10-09,41016,14666,5,26,32
29,30,Emp30,Finance,2018-01-21,95591,7892,10,18,41

In [ ]:
df.head()

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays
0,1,Emp1,IT,2018-10-04,50627,9892,10,22,21
1,2,Emp2,Finance,2021-03-30,48792,8863,7,13,27
2,3,Emp3,HR,2019-04-05,113969,9916,10,6,1
3,4,Emp4,IT,2021-08-30,83001,10529,9,26,41
4,5,Emp5,IT,2018-01-22,116552,2878,12,8,44

In [ ]:
df.tail()

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays
25,26,Emp26,Sales,2022-03-09,72606,8736,14,3,26
26,27,Emp27,Sales,2021-02-28,51534,2391,3,12,8
27,28,Emp28,Sales,2022-02-17,80397,14706,1,6,36
28,29,Emp29,Finance,2019-10-09,41016,14666,5,26,32
29,30,Emp30,Finance,2018-01-21,95591,7892,10,18,41

In [ ]:
df.shape

(30, 9)

In [ ]:
df.columns

Index(['EmployeeID', 'Name', 'Department', 'JoiningDate', 'Salary', 'Bonus',
       'ExperienceYears', 'ProjectsCompleted', 'RemoteDays'],
      dtype='object')

In [ ]:
df.dtypes

EmployeeID                    int64
Name                         object
Department                   object
JoiningDate          datetime64[ns]
Salary                        int64
Bonus                         int64
ExperienceYears               int64
ProjectsCompleted             int64
RemoteDays                    int64
dtype: object

In [ ]:
df[["Name", "Department", "Salary","Bonus"]]

     Name Department  Salary  Bonus
0    Emp1         IT   50627   9892
1    Emp2    Finance   48792   8863
2    Emp3         HR  113969   9916
3    Emp4         IT   83001  10529
4    Emp5         IT  116552   2878
5    Emp6    Finance   63897  11268
6    Emp7         HR  108148   6887
7    Emp8         HR   63483  14185
8    Emp9         IT   88555   6859
9   Emp10      Sales   57159   8331
10  Emp11         IT   75920  10571
11  Emp12         IT  107121  10684
12  Emp13         IT  109479   9208
13  Emp14         IT   59457   7276
14  Emp15    Finance  106557   4062
15  Emp16         HR  117189  14076
16  Emp17    Finance  118953   2064
17  Emp18    Finance   92995  10006
18  Emp19    Finance   80757   4568
19  Emp20         IT   49692   7463
20  Emp21      Sales   85758   4027
21  Emp22         HR  112409   4695
22  Emp23      Sales  111211  11687
23  Emp24    Finance  105697   7258
24  Emp25    Finance   77065   7618
25  Emp26      Sales   72606   8736
26  Emp27      Sales   51534   2391
27  Emp28      Sales   80397  14706
28  Emp29    Finance   41016  14666
29  Emp30    Finance   95591   7892

In [ ]:
df[df["Salary"]>80000]

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays
2,3,Emp3,HR,2019-04-05,113969,9916,10,6,1
3,4,Emp4,IT,2021-08-30,83001,10529,9,26,41
4,5,Emp5,IT,2018-01-22,116552,2878,12,8,44
6,7,Emp7,HR,2020-01-18,108148,6887,9,14,27
8,9,Emp9,IT,2022-05-04,88555,6859,12,9,43
11,12,Emp12,IT,2019-05-26,107121,10684,7,18,29
12,13,Emp13,IT,2022-09-02,109479,9208,7,6,10
14,15,Emp15,Finance,2019-12-01,106557,4062,8,19,24
15,16,Emp16,HR,2020-09-02,117189,14076,5,28,38
16,17,Emp17,Finance,2022-12-12,118953,2064,3,3,32
17,18,Emp18,Finance,2018-07-09,92995,10006,12,29,0
18,19,Emp19,Finance,2020-08-15,80757,4568,8,4,26
20,21,Emp21,Sales,2020-08-15,85758,4027,11,6,40
21,22,Emp22,HR,2019-07-17,112409,4695,3,12,2
22,23,Emp23,Sales,2022-05-10,111211,11687,1,14,38
23,24,Emp24,Finance,2021-06-21,105697,7258,3,10,5
27,28,Emp28,Sales,2022-02-17,80397,14706,1,6,36
29,30,Emp30,Finance,2018-01-21,95591,7892,10,18,41

In [ ]:
df[(df["Department"]=="IT") | (df["Department"]=="Finance")&(df["ExperienceYears"]>5)]

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays
0,1,Emp1,IT,2018-10-04,50627,9892,10,22,21
1,2,Emp2,Finance,2021-03-30,48792,8863,7,13,27
3,4,Emp4,IT,2021-08-30,83001,10529,9,26,41
4,5,Emp5,IT,2018-01-22,116552,2878,12,8,44
5,6,Emp6,Finance,2018-09-10,63897,11268,7,14,5
8,9,Emp9,IT,2022-05-04,88555,6859,12,9,43
10,11,Emp11,IT,2020-12-18,75920,10571,1,12,19
11,12,Emp12,IT,2019-05-26,107121,10684,7,18,29
12,13,Emp13,IT,2022-09-02,109479,9208,7,6,10
13,14,Emp14,IT,2022-02-08,59457,7276,14,16,27
14,15,Emp15,Finance,2019-12-01,106557,4062,8,19,24
17,18,Emp18,Finance,2018-07-09,92995,10006,12,29,0
18,19,Emp19,Finance,2020-08-15,80757,4568,8,4,26
19,20,Emp20,IT,2019-11-18,49692,7463,6,22,12
29,30,Emp30,Finance,2018-01-21,95591,7892,10,18,41

In [ ]:
df.sort_values("Salary",ascending=False)

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays
16,17,Emp17,Finance,2022-12-12,118953,2064,3,3,32
15,16,Emp16,HR,2020-09-02,117189,14076,5,28,38
4,5,Emp5,IT,2018-01-22,116552,2878,12,8,44
2,3,Emp3,HR,2019-04-05,113969,9916,10,6,1
21,22,Emp22,HR,2019-07-17,112409,4695,3,12,2
22,23,Emp23,Sales,2022-05-10,111211,11687,1,14,38
12,13,Emp13,IT,2022-09-02,109479,9208,7,6,10
6,7,Emp7,HR,2020-01-18,108148,6887,9,14,27
11,12,Emp12,IT,2019-05-26,107121,10684,7,18,29
14,15,Emp15,Finance,2019-12-01,106557,4062,8,19,24
23,24,Emp24,Finance,2021-06-21,105697,7258,3,10,5
29,30,Emp30,Finance,2018-01-21,95591,7892,10,18,41
17,18,Emp18,Finance,2018-07-09,92995,10006,12,29,0
8,9,Emp9,IT,2022-05-04,88555,6859,12,9,43
20,21,Emp21,Sales,2020-08-15,85758,4027,11,6,40
3,4,Emp4,IT,2021-08-30,83001,10529,9,26,41
18,19,Emp19,Finance,2020-08-15,80757,4568,8,4,26
27,28,Emp28,Sales,2022-02-17,80397,14706,1,6,36
24,25,Emp25,Finance,2020-04-11,77065,7618,5,28,7
10,11,Emp11,IT,2020-12-18,75920,10571,1,12,19
25,26,Emp26,Sales,2022-03-09,72606,8736,14,3,26
5,6,Emp6,Finance,2018-09-10,63897,11268,7,14,5
7,8,Emp8,HR,2020-05-06,63483,14185,8,25,27
13,14,Emp14,IT,2022-02-08,59457,7276,14,16,27
9,10,Emp10,Sales,2019-04-20,57159,8331,2,27,43
26,27,Emp27,Sales,2021-02-28,51534,2391,3,12,8
0,1,Emp1,IT,2018-10-04,50627,9892,10,22,21
19,20,Emp20,IT,2019-11-18,49692,7463,6,22,12
1,2,Emp2,Finance,2021-03-30,48792,8863,7,13,27
28,29,Emp29,Finance,2019-10-09,41016,14666,5,26,32

In [ ]:
df["TotalCompensation"] = df["Salary"] + df["Bonus"]
df

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays,TotalCompensation
0,1,Emp1,IT,2018-10-04,50627,9892,10,22,21,60519
1,2,Emp2,Finance,2021-03-30,48792,8863,7,13,27,57655
2,3,Emp3,HR,2019-04-05,113969,9916,10,6,1,123885
3,4,Emp4,IT,2021-08-30,83001,10529,9,26,41,93530
4,5,Emp5,IT,2018-01-22,116552,2878,12,8,44,119430
5,6,Emp6,Finance,2018-09-10,63897,11268,7,14,5,75165
6,7,Emp7,HR,2020-01-18,108148,6887,9,14,27,115035
7,8,Emp8,HR,2020-05-06,63483,14185,8,25,27,77668
8,9,Emp9,IT,2022-05-04,88555,6859,12,9,43,95414
9,10,Emp10,Sales,2019-04-20,57159,8331,2,27,43,65490
10,11,Emp11,IT,2020-12-18,75920,10571,1,12,19,86491
11,12,Emp12,IT,2019-05-26,107121,10684,7,18,29,117805
12,13,Emp13,IT,2022-09-02,109479,9208,7,6,10,118687
13,14,Emp14,IT,2022-02-08,59457,7276,14,16,27,66733
14,15,Emp15,Finance,2019-12-01,106557,4062,8,19,24,110619
15,16,Emp16,HR,2020-09-02,117189,14076,5,28,38,131265
16,17,Emp17,Finance,2022-12-12,118953,2064,3,3,32,121017
17,18,Emp18,Finance,2018-07-09,92995,10006,12,29,0,103001
18,19,Emp19,Finance,2020-08-15,80757,4568,8,4,26,85325
19,20,Emp20,IT,2019-11-18,49692,7463,6,22,12,57155
20,21,Emp21,Sales,2020-08-15,85758,4027,11,6,40,89785
21,22,Emp22,HR,2019-07-17,112409,4695,3,12,2,117104
22,23,Emp23,Sales,2022-05-10,111211,11687,1,14,38,122898
23,24,Emp24,Finance,2021-06-21,105697,7258,3,10,5,112955
24,25,Emp25,Finance,2020-04-11,77065,7618,5,28,7,84683
25,26,Emp26,Sales,2022-03-09,72606,8736,14,3,26,81342
26,27,Emp27,Sales,2021-02-28,51534,2391,3,12,8,53925
27,28,Emp28,Sales,2022-02-17,80397,14706,1,6,36,95103
28,29,Emp29,Finance,2019-10-09,41016,14666,5,26,32,55682
29,30,Emp30,Finance,2018-01-21,95591,7892,10,18,41,103483

In [ ]:
df[df["TotalCompensation"]> 100000 ]

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays,TotalCompensation
2,3,Emp3,HR,2019-04-05,113969,9916,10,6,1,123885
4,5,Emp5,IT,2018-01-22,116552,2878,12,8,44,119430
6,7,Emp7,HR,2020-01-18,108148,6887,9,14,27,115035
11,12,Emp12,IT,2019-05-26,107121,10684,7,18,29,117805
12,13,Emp13,IT,2022-09-02,109479,9208,7,6,10,118687
14,15,Emp15,Finance,2019-12-01,106557,4062,8,19,24,110619
15,16,Emp16,HR,2020-09-02,117189,14076,5,28,38,131265
16,17,Emp17,Finance,2022-12-12,118953,2064,3,3,32,121017
17,18,Emp18,Finance,2018-07-09,92995,10006,12,29,0,103001
21,22,Emp22,HR,2019-07-17,112409,4695,3,12,2,117104
22,23,Emp23,Sales,2022-05-10,111211,11687,1,14,38,122898
23,24,Emp24,Finance,2021-06-21,105697,7258,3,10,5,112955
29,30,Emp30,Finance,2018-01-21,95591,7892,10,18,41,103483

In [ ]:
df.iloc[:10]

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays,TotalCompensation
0,1,Emp1,IT,2018-10-04,50627,9892,10,22,21,60519
1,2,Emp2,Finance,2021-03-30,48792,8863,7,13,27,57655
2,3,Emp3,HR,2019-04-05,113969,9916,10,6,1,123885
3,4,Emp4,IT,2021-08-30,83001,10529,9,26,41,93530
4,5,Emp5,IT,2018-01-22,116552,2878,12,8,44,119430
5,6,Emp6,Finance,2018-09-10,63897,11268,7,14,5,75165
6,7,Emp7,HR,2020-01-18,108148,6887,9,14,27,115035
7,8,Emp8,HR,2020-05-06,63483,14185,8,25,27,77668
8,9,Emp9,IT,2022-05-04,88555,6859,12,9,43,95414
9,10,Emp10,Sales,2019-04-20,57159,8331,2,27,43,65490

In [ ]:
df.loc[df['Salary']==40000]

NameError: name 'df' is not defined

In [ ]:
df["Salary"].max()

118953

In [ ]:
df["Salary"].min()

41016

In [ ]:
df["Salary"].mean()

np.float64(84852.9)

In [ ]:
df.groupby("Department")["Salary"].mean()

Department
Finance     83132.000000
HR         103039.600000
IT          82267.111111
Sales       76444.166667
Name: Salary, dtype: float64

In [ ]:
df.groupby("Department")["Bonus"].sum()

Department
Finance    78265
HR         49759
IT         75360
Sales      49878
Name: Bonus, dtype: int64

In [ ]:
df.groupby("Department")["ExperienceYears"].mean()

Department
Finance    6.800000
HR         7.000000
IT         8.666667
Sales      5.333333
Name: ExperienceYears, dtype: float64

In [ ]:
df.groupby("Department")["ProjectsCompleted"].mean().idxmax()

'HR'

In [ ]:
df.groupby("Department").agg({"Salary":['max','min']})

            Salary
               max    min
Department
Finance     118953  41016
HR          117189  63483
IT          116552  49692
Sales       111211  51534

In [ ]:
df.groupby(["Department","ExperienceYears"]).agg({"Salary":'mean'})

                              Salary
Department ExperienceYears
Finance    3                112325.0
           5                 59040.5
           7                 56344.5
           8                 93657.0
           10                95591.0
           12                92995.0
HR         3                112409.0
           5                117189.0
           8                 63483.0
           9                108148.0
           10               113969.0
IT         1                 75920.0
           6                 49692.0
           7                108300.0
           9                 83001.0
           10                50627.0
           12               102553.5
           14                59457.0
Sales      1                 95804.0
           2                 57159.0
           3                 51534.0
           11                85758.0
           14                72606.0

In [ ]:
df["DepartmentAvgSalary"]=df.groupby("Department")["Salary"].transform('mean')
df

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays,TotalCompensation,DepartmentAvgSalary
0,1,Emp1,IT,2018-10-04,50627,9892,10,22,21,60519,82267.111111
1,2,Emp2,Finance,2021-03-30,48792,8863,7,13,27,57655,83132.000000
2,3,Emp3,HR,2019-04-05,113969,9916,10,6,1,123885,103039.600000
3,4,Emp4,IT,2021-08-30,83001,10529,9,26,41,93530,82267.111111
4,5,Emp5,IT,2018-01-22,116552,2878,12,8,44,119430,82267.111111
5,6,Emp6,Finance,2018-09-10,63897,11268,7,14,5,75165,83132.000000
6,7,Emp7,HR,2020-01-18,108148,6887,9,14,27,115035,103039.600000
7,8,Emp8,HR,2020-05-06,63483,14185,8,25,27,77668,103039.600000
8,9,Emp9,IT,2022-05-04,88555,6859,12,9,43,95414,82267.111111
9,10,Emp10,Sales,2019-04-20,57159,8331,2,27,43,65490,76444.166667
10,11,Emp11,IT,2020-12-18,75920,10571,1,12,19,86491,82267.111111
11,12,Emp12,IT,2019-05-26,107121,10684,7,18,29,117805,82267.111111
12,13,Emp13,IT,2022-09-02,109479,9208,7,6,10,118687,82267.111111
13,14,Emp14,IT,2022-02-08,59457,7276,14,16,27,66733,82267.111111
14,15,Emp15,Finance,2019-12-01,106557,4062,8,19,24,110619,83132.000000
15,16,Emp16,HR,2020-09-02,117189,14076,5,28,38,131265,103039.600000
16,17,Emp17,Finance,2022-12-12,118953,2064,3,3,32,121017,83132.000000
17,18,Emp18,Finance,2018-07-09,92995,10006,12,29,0,103001,83132.000000
18,19,Emp19,Finance,2020-08-15,80757,4568,8,4,26,85325,83132.000000
19,20,Emp20,IT,2019-11-18,49692,7463,6,22,12,57155,82267.111111
20,21,Emp21,Sales,2020-08-15,85758,4027,11,6,40,89785,76444.166667
21,22,Emp22,HR,2019-07-17,112409,4695,3,12,2,117104,103039.600000
22,23,Emp23,Sales,2022-05-10,111211,11687,1,14,38,122898,76444.166667
23,24,Emp24,Finance,2021-06-21,105697,7258,3,10,5,112955,83132.000000
24,25,Emp25,Finance,2020-04-11,77065,7618,5,28,7,84683,83132.000000
25,26,Emp26,Sales,2022-03-09,72606,8736,14,3,26,81342,76444.166667
26,27,Emp27,Sales,2021-02-28,51534,2391,3,12,8,53925,76444.166667
27,28,Emp28,Sales,2022-02-17,80397,14706,1,6,36,95103,76444.166667
28,29,Emp29,Finance,2019-10-09,41016,14666,5,26,32,55682,83132.000000
29,30,Emp30,Finance,2018-01-21,95591,7892,10,18,41,103483,83132.000000

In [ ]:
dg=df.groupby("Department")["Salary"].transform('mean')
df[df["Salary"]>(df.groupby("Department")["Salary"].transform('mean'))]["Name"]

2      Emp3
3      Emp4
4      Emp5
6      Emp7
8      Emp9
11    Emp12
12    Emp13
14    Emp15
15    Emp16
16    Emp17
17    Emp18
20    Emp21
21    Emp22
22    Emp23
23    Emp24
27    Emp28
29    Emp30
Name: Name, dtype: object

In [ ]:
df.sort_values("JoiningDate", ascending=True,inplace=True)
df["CumSum"]=df.groupby("Department")["ProjectsCompleted"].cumsum()
df

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays,CumSum
29,30,Emp30,Finance,2018-01-21,95591,7892,10,18,41,18
4,5,Emp5,IT,2018-01-22,116552,2878,12,8,44,8
17,18,Emp18,Finance,2018-07-09,92995,10006,12,29,0,47
5,6,Emp6,Finance,2018-09-10,63897,11268,7,14,5,61
0,1,Emp1,IT,2018-10-04,50627,9892,10,22,21,30
2,3,Emp3,HR,2019-04-05,113969,9916,10,6,1,6
9,10,Emp10,Sales,2019-04-20,57159,8331,2,27,43,27
11,12,Emp12,IT,2019-05-26,107121,10684,7,18,29,48
21,22,Emp22,HR,2019-07-17,112409,4695,3,12,2,18
28,29,Emp29,Finance,2019-10-09,41016,14666,5,26,32,87
19,20,Emp20,IT,2019-11-18,49692,7463,6,22,12,70
14,15,Emp15,Finance,2019-12-01,106557,4062,8,19,24,106
6,7,Emp7,HR,2020-01-18,108148,6887,9,14,27,32
24,25,Emp25,Finance,2020-04-11,77065,7618,5,28,7,134
7,8,Emp8,HR,2020-05-06,63483,14185,8,25,27,57
20,21,Emp21,Sales,2020-08-15,85758,4027,11,6,40,33
18,19,Emp19,Finance,2020-08-15,80757,4568,8,4,26,138
15,16,Emp16,HR,2020-09-02,117189,14076,5,28,38,85
10,11,Emp11,IT,2020-12-18,75920,10571,1,12,19,82
26,27,Emp27,Sales,2021-02-28,51534,2391,3,12,8,45
1,2,Emp2,Finance,2021-03-30,48792,8863,7,13,27,151
23,24,Emp24,Finance,2021-06-21,105697,7258,3,10,5,161
3,4,Emp4,IT,2021-08-30,83001,10529,9,26,41,108
13,14,Emp14,IT,2022-02-08,59457,7276,14,16,27,124
27,28,Emp28,Sales,2022-02-17,80397,14706,1,6,36,51
25,26,Emp26,Sales,2022-03-09,72606,8736,14,3,26,54
8,9,Emp9,IT,2022-05-04,88555,6859,12,9,43,133
22,23,Emp23,Sales,2022-05-10,111211,11687,1,14,38,68
12,13,Emp13,IT,2022-09-02,109479,9208,7,6,10,139
16,17,Emp17,Finance,2022-12-12,118953,2064,3,3,32,164

In [ ]:
df["persentage"]=df["ProjectsCompleted"]/df.groupby("Department")["ProjectsCompleted"].transform('sum')*100

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays,persentage
0,1,Emp1,IT,2018-10-04,50627,9892,10,22,21,15.827338
1,2,Emp2,Finance,2021-03-30,48792,8863,7,13,27,7.926829
2,3,Emp3,HR,2019-04-05,113969,9916,10,6,1,7.058824
3,4,Emp4,IT,2021-08-30,83001,10529,9,26,41,18.705036
4,5,Emp5,IT,2018-01-22,116552,2878,12,8,44,5.755396
5,6,Emp6,Finance,2018-09-10,63897,11268,7,14,5,8.536585
6,7,Emp7,HR,2020-01-18,108148,6887,9,14,27,16.470588
7,8,Emp8,HR,2020-05-06,63483,14185,8,25,27,29.411765
8,9,Emp9,IT,2022-05-04,88555,6859,12,9,43,6.474820
9,10,Emp10,Sales,2019-04-20,57159,8331,2,27,43,39.705882
10,11,Emp11,IT,2020-12-18,75920,10571,1,12,19,8.633094
11,12,Emp12,IT,2019-05-26,107121,10684,7,18,29,12.949640
12,13,Emp13,IT,2022-09-02,109479,9208,7,6,10,4.316547
13,14,Emp14,IT,2022-02-08,59457,7276,14,16,27,11.510791
14,15,Emp15,Finance,2019-12-01,106557,4062,8,19,24,11.585366
15,16,Emp16,HR,2020-09-02,117189,14076,5,28,38,32.941176
16,17,Emp17,Finance,2022-12-12,118953,2064,3,3,32,1.829268
17,18,Emp18,Finance,2018-07-09,92995,10006,12,29,0,17.682927
18,19,Emp19,Finance,2020-08-15,80757,4568,8,4,26,2.439024
19,20,Emp20,IT,2019-11-18,49692,7463,6,22,12,15.827338
20,21,Emp21,Sales,2020-08-15,85758,4027,11,6,40,8.823529
21,22,Emp22,HR,2019-07-17,112409,4695,3,12,2,14.117647
22,23,Emp23,Sales,2022-05-10,111211,11687,1,14,38,20.588235
23,24,Emp24,Finance,2021-06-21,105697,7258,3,10,5,6.097561
24,25,Emp25,Finance,2020-04-11,77065,7618,5,28,7,17.073171
25,26,Emp26,Sales,2022-03-09,72606,8736,14,3,26,4.411765
26,27,Emp27,Sales,2021-02-28,51534,2391,3,12,8,17.647059
27,28,Emp28,Sales,2022-02-17,80397,14706,1,6,36,8.823529
28,29,Emp29,Finance,2019-10-09,41016,14666,5,26,32,15.853659
29,30,Emp30,Finance,2018-01-21,95591,7892,10,18,41,10.975610

In [ ]:
df["ProductivityScore"]=df["ProjectsCompleted"]/df["ExperienceYears"]
df

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays,persentage,ProductivityScore
0,1,Emp1,IT,2018-10-04,50627,9892,10,22,21,15.827338,2.200000
1,2,Emp2,Finance,2021-03-30,48792,8863,7,13,27,7.926829,1.857143
2,3,Emp3,HR,2019-04-05,113969,9916,10,6,1,7.058824,0.600000
3,4,Emp4,IT,2021-08-30,83001,10529,9,26,41,18.705036,2.888889
4,5,Emp5,IT,2018-01-22,116552,2878,12,8,44,5.755396,0.666667
5,6,Emp6,Finance,2018-09-10,63897,11268,7,14,5,8.536585,2.000000
6,7,Emp7,HR,2020-01-18,108148,6887,9,14,27,16.470588,1.555556
7,8,Emp8,HR,2020-05-06,63483,14185,8,25,27,29.411765,3.125000
8,9,Emp9,IT,2022-05-04,88555,6859,12,9,43,6.474820,0.750000
9,10,Emp10,Sales,2019-04-20,57159,8331,2,27,43,39.705882,13.500000
10,11,Emp11,IT,2020-12-18,75920,10571,1,12,19,8.633094,12.000000
11,12,Emp12,IT,2019-05-26,107121,10684,7,18,29,12.949640,2.571429
12,13,Emp13,IT,2022-09-02,109479,9208,7,6,10,4.316547,0.857143
13,14,Emp14,IT,2022-02-08,59457,7276,14,16,27,11.510791,1.142857
14,15,Emp15,Finance,2019-12-01,106557,4062,8,19,24,11.585366,2.375000
15,16,Emp16,HR,2020-09-02,117189,14076,5,28,38,32.941176,5.600000
16,17,Emp17,Finance,2022-12-12,118953,2064,3,3,32,1.829268,1.000000
17,18,Emp18,Finance,2018-07-09,92995,10006,12,29,0,17.682927,2.416667
18,19,Emp19,Finance,2020-08-15,80757,4568,8,4,26,2.439024,0.500000
19,20,Emp20,IT,2019-11-18,49692,7463,6,22,12,15.827338,3.666667
20,21,Emp21,Sales,2020-08-15,85758,4027,11,6,40,8.823529,0.545455
21,22,Emp22,HR,2019-07-17,112409,4695,3,12,2,14.117647,4.000000
22,23,Emp23,Sales,2022-05-10,111211,11687,1,14,38,20.588235,14.000000
23,24,Emp24,Finance,2021-06-21,105697,7258,3,10,5,6.097561,3.333333
24,25,Emp25,Finance,2020-04-11,77065,7618,5,28,7,17.073171,5.600000
25,26,Emp26,Sales,2022-03-09,72606,8736,14,3,26,4.411765,0.214286
26,27,Emp27,Sales,2021-02-28,51534,2391,3,12,8,17.647059,4.000000
27,28,Emp28,Sales,2022-02-17,80397,14706,1,6,36,8.823529,6.000000
28,29,Emp29,Finance,2019-10-09,41016,14666,5,26,32,15.853659,5.200000
29,30,Emp30,Finance,2018-01-21,95591,7892,10,18,41,10.975610,1.800000

In [ ]:
df.sort_values(by="ProductivityScore",ascending=False).head(5)

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays,Cem,persentage,ProductivityScore
22,23,Emp23,Sales,2022-05-10,111211,11687,1,14,38,68,20.588235,14.0
9,10,Emp10,Sales,2019-04-20,57159,8331,2,27,43,27,39.705882,13.5
10,11,Emp11,IT,2020-12-18,75920,10571,1,12,19,82,8.633094,12.0
27,28,Emp28,Sales,2022-02-17,80397,14706,1,6,36,51,8.823529,6.0
15,16,Emp16,HR,2020-09-02,117189,14076,5,28,38,85,32.941176,5.6

In [ ]:
df.groupby("ExperienceYears")["Salary"].mean()

ExperienceYears
1     89176.000000
2     57159.000000
3     97148.250000
5     78423.333333
6     49692.000000
7     82322.250000
8     83599.000000
9     95574.500000
10    86729.000000
11    85758.000000
12    99367.333333
14    66031.500000
Name: Salary, dtype: float64

In [ ]:
df[(df["ExperienceYears"]<4) & (df["Salary"]>80000)]["Name"]

16    Emp17
21    Emp22
22    Emp23
23    Emp24
27    Emp28
Name: Name, dtype: object

In [ ]:
dg=df.groupby("Department")["Salary"].transform('median')

In [ ]:
df[(df["ProductivityScore"]> 1.5) & (df["Salary"] > dg)]

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays,persentage,ProductivityScore
11,12,Emp12,IT,2019-05-26,107121,10684,7,18,29,12.949640,2.571429
14,15,Emp15,Finance,2019-12-01,106557,4062,8,19,24,11.585366,2.375000
15,16,Emp16,HR,2020-09-02,117189,14076,5,28,38,32.941176,5.600000
17,18,Emp18,Finance,2018-07-09,92995,10006,12,29,0,17.682927,2.416667
22,23,Emp23,Sales,2022-05-10,111211,11687,1,14,38,20.588235,14.000000
23,24,Emp24,Finance,2021-06-21,105697,7258,3,10,5,6.097561,3.333333
27,28,Emp28,Sales,2022-02-17,80397,14706,1,6,36,8.823529,6.000000
29,30,Emp30,Finance,2018-01-21,95591,7892,10,18,41,10.975610,1.800000

In [ ]:
df[["Salary","Bonus","ExperienceYears","ProjectsCompleted","RemoteDays"]].corr()

,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays
Salary,1.000000,-0.219575,-0.017470,-0.312669,0.034745
Bonus,-0.219575,1.000000,-0.166876,0.430882,0.068628
ExperienceYears,-0.017470,-0.166876,1.000000,-0.056945,0.104468
ProjectsCompleted,-0.312669,0.430882,-0.056945,1.000000,0.007159
RemoteDays,0.034745,0.068628,0.104468,0.007159,1.000000

In [ ]:
df["TotalCompensation"]=df["Salary"]+df["Bonus"]
df[["TotalCompensation","Salary","Bonus","ExperienceYears","ProjectsCompleted","RemoteDays"]].corr().max()

TotalCompensation    1.0
Salary               1.0
Bonus                1.0
ExperienceYears      1.0
ProjectsCompleted    1.0
RemoteDays           1.0
dtype: float64

In [ ]:
df[(df["ExperienceYears"]>3)&(df["ProjectsCompleted"]<10)&(df["RemoteDays"]>=40)]["Name"]

4      Emp5
8      Emp9
20    Emp21
Name: Name, dtype: object

In [ ]:
a=df.groupby("Department")["Salary"].transform('sum')
b=df.groupby("Department")["Department"].transform('count')
df["Bns2"]=(a/b)*0.1
df["compare"]=df["Bonus"]-df["Bns2"]
df

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays,Bns2,compare
0,1,Emp1,IT,2018-10-04,50627,9892,10,22,21,8226.711111,1665.288889
1,2,Emp2,Finance,2021-03-30,48792,8863,7,13,27,8313.200000,549.800000
2,3,Emp3,HR,2019-04-05,113969,9916,10,6,1,10303.960000,-387.960000
3,4,Emp4,IT,2021-08-30,83001,10529,9,26,41,8226.711111,2302.288889
4,5,Emp5,IT,2018-01-22,116552,2878,12,8,44,8226.711111,-5348.711111
5,6,Emp6,Finance,2018-09-10,63897,11268,7,14,5,8313.200000,2954.800000
6,7,Emp7,HR,2020-01-18,108148,6887,9,14,27,10303.960000,-3416.960000
7,8,Emp8,HR,2020-05-06,63483,14185,8,25,27,10303.960000,3881.040000
8,9,Emp9,IT,2022-05-04,88555,6859,12,9,43,8226.711111,-1367.711111
9,10,Emp10,Sales,2019-04-20,57159,8331,2,27,43,7644.416667,686.583333
10,11,Emp11,IT,2020-12-18,75920,10571,1,12,19,8226.711111,2344.288889
11,12,Emp12,IT,2019-05-26,107121,10684,7,18,29,8226.711111,2457.288889
12,13,Emp13,IT,2022-09-02,109479,9208,7,6,10,8226.711111,981.288889
13,14,Emp14,IT,2022-02-08,59457,7276,14,16,27,8226.711111,-950.711111
14,15,Emp15,Finance,2019-12-01,106557,4062,8,19,24,8313.200000,-4251.200000
15,16,Emp16,HR,2020-09-02,117189,14076,5,28,38,10303.960000,3772.040000
16,17,Emp17,Finance,2022-12-12,118953,2064,3,3,32,8313.200000,-6249.200000
17,18,Emp18,Finance,2018-07-09,92995,10006,12,29,0,8313.200000,1692.800000
18,19,Emp19,Finance,2020-08-15,80757,4568,8,4,26,8313.200000,-3745.200000
19,20,Emp20,IT,2019-11-18,49692,7463,6,22,12,8226.711111,-763.711111
20,21,Emp21,Sales,2020-08-15,85758,4027,11,6,40,7644.416667,-3617.416667
21,22,Emp22,HR,2019-07-17,112409,4695,3,12,2,10303.960000,-5608.960000
22,23,Emp23,Sales,2022-05-10,111211,11687,1,14,38,7644.416667,4042.583333
23,24,Emp24,Finance,2021-06-21,105697,7258,3,10,5,8313.200000,-1055.200000
24,25,Emp25,Finance,2020-04-11,77065,7618,5,28,7,8313.200000,-695.200000
25,26,Emp26,Sales,2022-03-09,72606,8736,14,3,26,7644.416667,1091.583333
26,27,Emp27,Sales,2021-02-28,51534,2391,3,12,8,7644.416667,-5253.416667
27,28,Emp28,Sales,2022-02-17,80397,14706,1,6,36,7644.416667,7061.583333
28,29,Emp29,Finance,2019-10-09,41016,14666,5,26,32,8313.200000,6352.800000
29,30,Emp30,Finance,2018-01-21,95591,7892,10,18,41,8313.200000,-421.200000

In [ ]:
df

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays,Bns2,compare
0,1,Emp1,IT,2018-10-04,50627,9892,10,22,21,8226.711111,1665.288889
1,2,Emp2,Finance,2021-03-30,48792,8863,7,13,27,8313.200000,549.800000
2,3,Emp3,HR,2019-04-05,113969,9916,10,6,1,10303.960000,-387.960000
3,4,Emp4,IT,2021-08-30,83001,10529,9,26,41,8226.711111,2302.288889
4,5,Emp5,IT,2018-01-22,116552,2878,12,8,44,8226.711111,-5348.711111
5,6,Emp6,Finance,2018-09-10,63897,11268,7,14,5,8313.200000,2954.800000
6,7,Emp7,HR,2020-01-18,108148,6887,9,14,27,10303.960000,-3416.960000
7,8,Emp8,HR,2020-05-06,63483,14185,8,25,27,10303.960000,3881.040000
8,9,Emp9,IT,2022-05-04,88555,6859,12,9,43,8226.711111,-1367.711111
9,10,Emp10,Sales,2019-04-20,57159,8331,2,27,43,7644.416667,686.583333
10,11,Emp11,IT,2020-12-18,75920,10571,1,12,19,8226.711111,2344.288889
11,12,Emp12,IT,2019-05-26,107121,10684,7,18,29,8226.711111,2457.288889
12,13,Emp13,IT,2022-09-02,109479,9208,7,6,10,8226.711111,981.288889
13,14,Emp14,IT,2022-02-08,59457,7276,14,16,27,8226.711111,-950.711111
14,15,Emp15,Finance,2019-12-01,106557,4062,8,19,24,8313.200000,-4251.200000
15,16,Emp16,HR,2020-09-02,117189,14076,5,28,38,10303.960000,3772.040000
16,17,Emp17,Finance,2022-12-12,118953,2064,3,3,32,8313.200000,-6249.200000
17,18,Emp18,Finance,2018-07-09,92995,10006,12,29,0,8313.200000,1692.800000
18,19,Emp19,Finance,2020-08-15,80757,4568,8,4,26,8313.200000,-3745.200000
19,20,Emp20,IT,2019-11-18,49692,7463,6,22,12,8226.711111,-763.711111
20,21,Emp21,Sales,2020-08-15,85758,4027,11,6,40,7644.416667,-3617.416667
21,22,Emp22,HR,2019-07-17,112409,4695,3,12,2,10303.960000,-5608.960000
22,23,Emp23,Sales,2022-05-10,111211,11687,1,14,38,7644.416667,4042.583333
23,24,Emp24,Finance,2021-06-21,105697,7258,3,10,5,8313.200000,-1055.200000
24,25,Emp25,Finance,2020-04-11,77065,7618,5,28,7,8313.200000,-695.200000
25,26,Emp26,Sales,2022-03-09,72606,8736,14,3,26,7644.416667,1091.583333
26,27,Emp27,Sales,2021-02-28,51534,2391,3,12,8,7644.416667,-5253.416667
27,28,Emp28,Sales,2022-02-17,80397,14706,1,6,36,7644.416667,7061.583333
28,29,Emp29,Finance,2019-10-09,41016,14666,5,26,32,8313.200000,6352.800000
29,30,Emp30,Finance,2018-01-21,95591,7892,10,18,41,8313.200000,-421.200000

In [ ]:
lshp=df[(df["Salary"]<60000)&(df["ProjectsCompleted"]>7)]

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays,Bns2,compare
0,1,Emp1,IT,2018-10-04,50627,9892,10,22,21,8226.711111,1665.288889
1,2,Emp2,Finance,2021-03-30,48792,8863,7,13,27,8313.200000,549.800000
9,10,Emp10,Sales,2019-04-20,57159,8331,2,27,43,7644.416667,686.583333
13,14,Emp14,IT,2022-02-08,59457,7276,14,16,27,8226.711111,-950.711111
19,20,Emp20,IT,2019-11-18,49692,7463,6,22,12,8226.711111,-763.711111
26,27,Emp27,Sales,2021-02-28,51534,2391,3,12,8,7644.416667,-5253.416667
28,29,Emp29,Finance,2019-10-09,41016,14666,5,26,32,8313.200000,6352.800000

In [ ]:
hslp=df[(df["Salary"]>90000)&(df["ProjectsCompleted"]<10)]
hslp

,EmployeeID,Name,Department,JoiningDate,Salary,Bonus,ExperienceYears,ProjectsCompleted,RemoteDays,Bns2,compare
2,3,Emp3,HR,2019-04-05,113969,9916,10,6,1,10303.960000,-387.960000
4,5,Emp5,IT,2018-01-22,116552,2878,12,8,44,8226.711111,-5348.711111
12,13,Emp13,IT,2022-09-02,109479,9208,7,6,10,8226.711111,981.288889
16,17,Emp17,Finance,2022-12-12,118953,2064,3,3,32,8313.200000,-6249.200000