<a href="https://colab.research.google.com/github/Ayan282/colab/blob/main/statistikaa1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving Data (2).xlsx to Data (2).xlsx

In [2]:
import pandas as pd
df = pd.read_excel("Data (2).xlsx")

In [3]:
df

,Student_ID,Gender,Age,Department,Education_Level,Region,Height,Weight,Exam_Score,Salary,Product_Category,Sales
0,1,Male,20,IT,Bachelor,Baku,175,70,78,800,Electronics,1200
1,2,Female,22,Finance,Bachelor,Ganja,165,58,85,750,Clothing,900
2,3,Male,21,IT,Bachelor,Baku,180,80,90,900,Electronics,1500
3,4,Female,23,Marketing,Master,Sumqayit,168,60,72,700,Beauty,600
4,5,Male,24,Finance,Master,Baku,172,75,88,950,Electronics,2000
5,6,Female,20,IT,Bachelor,Ganja,160,55,91,780,Clothing,850
6,7,Male,22,Marketing,Bachelor,Baku,178,82,65,650,Food,400
7,8,Female,21,Finance,Bachelor,Sumqayit,162,57,79,720,Beauty,500
8,9,Male,23,IT,Master,Baku,185,90,84,1000,Electronics,2500
9,10,Female,24,Marketing,Master,Ganja,170,63,92,1100,Clothing,1300
10,11,Male,22,Finance,Bachelor,Baku,176,77,73,680,Food,450
11,12,Female,21,IT,Bachelor,Sumqayit,164,59,87,820,Electronics,1600
12,13,Male,25,Marketing,PhD,Baku,182,85,95,1500,Electronics,3000
13,14,Female,23,Finance,Master,Ganja,166,61,81,900,Beauty,700
14,15,Male,20,IT,Bachelor,Baku,174,72,69,600,Food,350
15,16,Female,22,Marketing,Bachelor,Sumqayit,169,64,76,740,Clothing,950
16,17,Male,24,Finance,Master,Baku,177,79,89,980,Electronics,2200
17,18,Female,21,IT,Bachelor,Ganja,161,56,93,860,Beauty,650
18,19,Male,23,Marketing,Master,Baku,183,88,71,690,Food,500
19,20,Female,25,Finance,PhD,Baku,167,62,97,1600,Electronics,3200

In [ ]:
df.groupby("Department").agg({'Age':['mean','median']})

                  Age
                 mean median
Department
Finance     23.000000   23.0
IT          20.857143   21.0
Marketing   23.166667   23.0

In [ ]:
df.groupby("Department").agg({'Exam_Score':['min','max']})

           Exam_Score
                  min max
Department
Finance            73  97
IT                 69  93
Marketing          65  95

In [ ]:
df["range"]=df["Salary"].max()-df["Salary"].min()

,Student_ID,Gender,Age,Department,Education_Level,Region,Height,Weight,Exam_Score,Salary,Product_Category,Sales,range
0,1,Male,20,IT,Bachelor,Baku,175,70,78,800,Electronics,1200,1000
1,2,Female,22,Finance,Bachelor,Ganja,165,58,85,750,Clothing,900,1000
2,3,Male,21,IT,Bachelor,Baku,180,80,90,900,Electronics,1500,1000
3,4,Female,23,Marketing,Master,Sumqayit,168,60,72,700,Beauty,600,1000
4,5,Male,24,Finance,Master,Baku,172,75,88,950,Electronics,2000,1000
5,6,Female,20,IT,Bachelor,Ganja,160,55,91,780,Clothing,850,1000
6,7,Male,22,Marketing,Bachelor,Baku,178,82,65,650,Food,400,1000
7,8,Female,21,Finance,Bachelor,Sumqayit,162,57,79,720,Beauty,500,1000
8,9,Male,23,IT,Master,Baku,185,90,84,1000,Electronics,2500,1000
9,10,Female,24,Marketing,Master,Ganja,170,63,92,1100,Clothing,1300,1000
10,11,Male,22,Finance,Bachelor,Baku,176,77,73,680,Food,450,1000
11,12,Female,21,IT,Bachelor,Sumqayit,164,59,87,820,Electronics,1600,1000
12,13,Male,25,Marketing,PhD,Baku,182,85,95,1500,Electronics,3000,1000
13,14,Female,23,Finance,Master,Ganja,166,61,81,900,Beauty,700,1000
14,15,Male,20,IT,Bachelor,Baku,174,72,69,600,Food,350,1000
15,16,Female,22,Marketing,Bachelor,Sumqayit,169,64,76,740,Clothing,950,1000
16,17,Male,24,Finance,Master,Baku,177,79,89,980,Electronics,2200,1000
17,18,Female,21,IT,Bachelor,Ganja,161,56,93,860,Beauty,650,1000
18,19,Male,23,Marketing,Master,Baku,183,88,71,690,Food,500,1000
19,20,Female,25,Finance,PhD,Baku,167,62,97,1600,Electronics,3200,1000

salary sutunundaki max ve min deyerler ferqi 1000 olduguna gore range=1000

In [ ]:
df[['Weight','Height']].cov()

            Weight     Height
Weight  133.397368  86.152632
Height   86.152632  58.431579

eger + olarsa eyni istiqametli hereket edir weight artdiqda height de artir

In [ ]:
df[['Weight','Height']].corr()

          Weight    Height
Weight  1.000000  0.975823
Height  0.975823  1.000000

In [ ]:
df['Q1']=df['Exam_Score'].quantile(0.25)
df['Q2']=df['Exam_Score'].quantile(0.50)
df['Q3']=df['Exam_Score'].quantile(0.75)

In [10]:
df['Q1']=df['Salary'].quantile(0.25)
df['Q2']=df['Salary'].quantile(0.50)
df['Q3']=df['Salary'].quantile(0.75)
IQR=df['Q3']-df['Q1']

In [ ]:
df['Exam_Score'].std()

9.441649053110652

In [ ]:
df[['Weight','Height']].cov()

            Weight     Height
Weight  133.397368  86.152632
Height   86.152632  58.431579

In [ ]:
df[['Weight','Height']].corr()

          Weight    Height
Weight  1.000000  0.975823
Height  0.975823  1.000000

In [ ]:
df.groupby("Department")["Exam_Score"].mean()

Department
Finance      84.571429
IT           84.571429
Marketing    78.500000
Name: Exam_Score, dtype: float64

Finance,IT deparmentde exam scorun orta qiymeti eynidir amma Marketing nisbeten azdir

In [6]:
df["Sales"].std()

883.5149598113924

In [7]:
df["Salary"].std()

261.8637653035398

In [8]:
df["Sales"].var()

780598.6842105263

In [9]:
df["Salary"].var()

68572.63157894737

Sales daha deyiskendir

In [14]:
df['Q1']=df['Height'].quantile(0.25)
df['Q2']=df['Height'].quantile(0.50)
df['Q3']=df['Height'].quantile(0.75)
IQR=df['Q3']-df['Q1']
min_outlier=df["Q1"]-1.5*IQR
max_outlier=df["Q3"]+ 1.5*IQR

In [13]:
min_outlier

0     148.5
1     148.5
2     148.5
3     148.5
4     148.5
5     148.5
6     148.5
7     148.5
8     148.5
9     148.5
10    148.5
11    148.5
12    148.5
13    148.5
14    148.5
15    148.5
16    148.5
17    148.5
18    148.5
19    148.5
dtype: float64

In [15]:
max_outlier

0     194.5
1     194.5
2     194.5
3     194.5
4     194.5
5     194.5
6     194.5
7     194.5
8     194.5
9     194.5
10    194.5
11    194.5
12    194.5
13    194.5
14    194.5
15    194.5
16    194.5
17    194.5
18    194.5
19    194.5
dtype: float64

In [16]:
df[['Age','Salary']].corr()

             Age    Salary
Age     1.000000  0.716001
Salary  0.716001  1.000000

In [ ]:
Age ve Salary sutunu arasindaki elaqe gucludur

In [17]:
df[['Age','Salary']].cov()

               Age        Salary
Age       2.536842    298.631579
Salary  298.631579  68572.631579

yas artdiqca maas artir

In [18]:
df[['Exam_Score','Salary']].corr()

            Exam_Score    Salary
Exam_Score    1.000000  0.756555
Salary        0.756555  1.000000

bu elaqe cox menali olmaya biler cunki exam score maasa bir basa tesir eden amil deyil

In [19]:
df[['Height','Weight']].corr()

          Height    Weight
Height  1.000000  0.975823
Weight  0.975823  1.000000

en mentiqli elaqe ceki ve uzunluq arasindadir burada elaqe daha gucludur

In [20]:
df[['Exam_Score','Salary']].corr()

            Exam_Score    Salary
Exam_Score    1.000000  0.756555
Salary        0.756555  1.000000

In [21]:
df[['Exam_Score','Age']].corr()

            Exam_Score       Age
Exam_Score    1.000000  0.351737
Age           0.351737  1.000000