<a href="https://colab.research.google.com/github/Ayan282/colab/blob/main/statistika1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Data (2).xlsx to Data (2).xlsx

In [4]:
import pandas as pd
df = pd.read_excel("Data (2).xlsx")

In [5]:
df

,Student_ID,Gender,Age,Department,Education_Level,Region,Height,Weight,Exam_Score,Salary,Product_Category,Sales
0,1,Male,20,IT,Bachelor,Baku,175,70,78,800,Electronics,1200
1,2,Female,22,Finance,Bachelor,Ganja,165,58,85,750,Clothing,900
2,3,Male,21,IT,Bachelor,Baku,180,80,90,900,Electronics,1500
3,4,Female,23,Marketing,Master,Sumqayit,168,60,72,700,Beauty,600
4,5,Male,24,Finance,Master,Baku,172,75,88,950,Electronics,2000
5,6,Female,20,IT,Bachelor,Ganja,160,55,91,780,Clothing,850
6,7,Male,22,Marketing,Bachelor,Baku,178,82,65,650,Food,400
7,8,Female,21,Finance,Bachelor,Sumqayit,162,57,79,720,Beauty,500
8,9,Male,23,IT,Master,Baku,185,90,84,1000,Electronics,2500
9,10,Female,24,Marketing,Master,Ganja,170,63,92,1100,Clothing,1300
10,11,Male,22,Finance,Bachelor,Baku,176,77,73,680,Food,450
11,12,Female,21,IT,Bachelor,Sumqayit,164,59,87,820,Electronics,1600
12,13,Male,25,Marketing,PhD,Baku,182,85,95,1500,Electronics,3000
13,14,Female,23,Finance,Master,Ganja,166,61,81,900,Beauty,700
14,15,Male,20,IT,Bachelor,Baku,174,72,69,600,Food,350
15,16,Female,22,Marketing,Bachelor,Sumqayit,169,64,76,740,Clothing,950
16,17,Male,24,Finance,Master,Baku,177,79,89,980,Electronics,2200
17,18,Female,21,IT,Bachelor,Ganja,161,56,93,860,Beauty,650
18,19,Male,23,Marketing,Master,Baku,183,88,71,690,Food,500
19,20,Female,25,Finance,PhD,Baku,167,62,97,1600,Electronics,3200

In [16]:
df.groupby("Department").agg({'Age':['mean','median']})

                  Age
                 mean median
Department
Finance     23.000000   23.0
IT          20.857143   21.0
Marketing   23.166667   23.0

In [18]:
df.groupby("Department").agg({'Exam_Score':['min','max']})

           Exam_Score
                  min max
Department
Finance            73  97
IT                 69  93
Marketing          65  95

In [20]:
df["range"]=df["Salary"].max()-df["Salary"].min()

,Student_ID,Gender,Age,Department,Education_Level,Region,Height,Weight,Exam_Score,Salary,Product_Category,Sales,range
0,1,Male,20,IT,Bachelor,Baku,175,70,78,800,Electronics,1200,1000
1,2,Female,22,Finance,Bachelor,Ganja,165,58,85,750,Clothing,900,1000
2,3,Male,21,IT,Bachelor,Baku,180,80,90,900,Electronics,1500,1000
3,4,Female,23,Marketing,Master,Sumqayit,168,60,72,700,Beauty,600,1000
4,5,Male,24,Finance,Master,Baku,172,75,88,950,Electronics,2000,1000
5,6,Female,20,IT,Bachelor,Ganja,160,55,91,780,Clothing,850,1000
6,7,Male,22,Marketing,Bachelor,Baku,178,82,65,650,Food,400,1000
7,8,Female,21,Finance,Bachelor,Sumqayit,162,57,79,720,Beauty,500,1000
8,9,Male,23,IT,Master,Baku,185,90,84,1000,Electronics,2500,1000
9,10,Female,24,Marketing,Master,Ganja,170,63,92,1100,Clothing,1300,1000
10,11,Male,22,Finance,Bachelor,Baku,176,77,73,680,Food,450,1000
11,12,Female,21,IT,Bachelor,Sumqayit,164,59,87,820,Electronics,1600,1000
12,13,Male,25,Marketing,PhD,Baku,182,85,95,1500,Electronics,3000,1000
13,14,Female,23,Finance,Master,Ganja,166,61,81,900,Beauty,700,1000
14,15,Male,20,IT,Bachelor,Baku,174,72,69,600,Food,350,1000
15,16,Female,22,Marketing,Bachelor,Sumqayit,169,64,76,740,Clothing,950,1000
16,17,Male,24,Finance,Master,Baku,177,79,89,980,Electronics,2200,1000
17,18,Female,21,IT,Bachelor,Ganja,161,56,93,860,Beauty,650,1000
18,19,Male,23,Marketing,Master,Baku,183,88,71,690,Food,500,1000
19,20,Female,25,Finance,PhD,Baku,167,62,97,1600,Electronics,3200,1000

salary sutunundaki max ve min deyerler ferqi 1000 olduguna gore range=1000

In [29]:
df[['Weight','Height']].cov()

            Weight     Height
Weight  133.397368  86.152632
Height   86.152632  58.431579

eger + olarsa eyni istiqametli hereket edir weight artdiqda height de artir

In [30]:
df[['Weight','Height']].corr()

          Weight    Height
Weight  1.000000  0.975823
Height  0.975823  1.000000

In [33]:
df['Q1']=df['Exam_Score'].quantile(0.25)
df['Q2']=df['Exam_Score'].quantile(0.50)
df['Q3']=df['Exam_Score'].quantile(0.75)

In [37]:
df['Q1']=df['Salary'].quantile(0.25)
df['Q2']=df['Salary'].quantile(0.50)
df['Q3']=df['Salary'].quantile(0.75)
IQR=df['Q3']-df['Q1']

0     242.5
1     242.5
2     242.5
3     242.5
4     242.5
5     242.5
6     242.5
7     242.5
8     242.5
9     242.5
10    242.5
11    242.5
12    242.5
13    242.5
14    242.5
15    242.5
16    242.5
17    242.5
18    242.5
19    242.5
dtype: float64

In [39]:
df['Exam_Score'].std()

9.441649053110652

In [40]:
df[['Weight','Height']].cov()

            Weight     Height
Weight  133.397368  86.152632
Height   86.152632  58.431579

In [41]:
df[['Weight','Height']].corr()

          Weight    Height
Weight  1.000000  0.975823
Height  0.975823  1.000000

In [43]:
df.groupby("Department")["Exam_Score"].mean()

Department
Finance      84.571429
IT           84.571429
Marketing    78.500000
Name: Exam_Score, dtype: float64

Finance,IT deparmentde exam scorun orta qiymeti eynidir amma Marketing nisbeten azdir